apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: ztre-test
  labels:
    app: database
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: ztre-test
  labels:
    app: database
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        tier: backend
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: "supersecret123"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "bankdb"
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
