apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  namespace: ztre-test
  labels:
    app: vulnerable-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
        tier: frontend
    spec:
      containers:
      - name: app
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Vulnerable microservice running..."
          while true; do sleep 3600; done
        resources:
          requests:
            cpu: 20m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
